<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ApexHack.Loader</RootNamespace>
    <AssemblyName>apexhack</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../apex-legends-hack.Core/apex-legends-hack.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
